BAP:
  $ref: ./IGM/BAP/index.yaml
BPP:
  $ref: ./IGM/BPP/index.yaml
schema:
  $ref: ./schema/IGM/index.yaml
# attributes:
#   personal-loan-flow-1:
#     $ref: ./attributes/personal-loan-flow-1/index.yaml
#   invoice-loan-flow-1:
#     $ref: ./attributes/invoice-loan-flow-1/index.yaml
version: "1.0.0"